Develop
daicha-w/PaletteCloud_tutorial_1 pull request #1
Opened 2022-02-12 03:07 UTC by daicha-w

2022-02-12 05:54 UTC, gonzaemon111 requested changes

2022-02-12 05:54 UTC, gonzaemon111 commented on app/controllers/posts_controller.rb
> +    @posts = Post.all.order(created_at: 'desc')
`'desc'`のところは、なるべく、stringではなく、シンボルを使いましょう！
理由は、rubyの場合、stringよりもシンボルの方が処理が早いからです

```rb
@posts = Post.all.order(created_at: :desc)
```

2022-02-12 05:54 UTC, gonzaemon111 commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
```rb
@post = Post.find(params[:id])
```

この行は、editやdestroy、updateでも使います。
そのため、privateメソッドで以下の様にしましょう！

```rb
# editなども
def show; end

def update
  if post.update(post_params)
    ...
  else
    ...
  end
end

private

def post
  # ポイント1
  @post ||= ::Post.find(params[:id])
end
# ポイント2
helper_method :post
```

- ポイント１
  - Ruby独特な書き方で、`||=`という記法があリます。これは、`@post`に代入されているときは、それを返すし、`@post`がnilの時は、右側を実行し、代入するという文です。（補足になりますが、Rubyはreturn文を明示しなくてもメソッドの最後の文が暗黙的にreturnされます。そのため、今回は、postメソッドでは、@postがreturnされます。）
- ポイント2
  - この様にhelper_methodを追加すると、viewでpostメソッドを呼び出すことができます。


参考文献 : 

https://qiita.com/nikadon/items/41da819f0aa698d74e7d#%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E5%A4%89%E6%95%B0%E3%82%92%E3%83%A1%E3%83%A2%E5%8C%96%E3%81%99%E3%82%8B

これは社員さんが書いた記事なので、一読してみてください！

2022-02-12 05:54 UTC, gonzaemon111 commented on app/controllers/posts_controller.rb
> +      render 'new'
ここもシンボルにしましょう

```rb
  render :new
```

2022-02-12 05:54 UTC, gonzaemon111 commented on app/controllers/posts_controller.rb
> +      render 'edit'
ここもシンボル

2022-02-12 05:54 UTC, gonzaemon111 commented on app/controllers/posts_controller.rb
> +    @post.destroy
上のshowコメントと合わせて、いかにする

```rb
def destroy
  post.destroy
  redirect_to ...
end
```

2022-02-12 05:54 UTC, gonzaemon111 commented on app/helpers/posts_helper.rb
> +module PostsHelper
同様

2022-02-12 05:54 UTC, gonzaemon111 commented on app/models/post.rb
> +  has_many :comments, dependent: :destroy
ここもclass_nameを

2022-02-12 05:54 UTC, gonzaemon111 commented on app/views/posts/_form.html.erb
> +  <span class="error"><%= @post.errors.messages[:title][0] %></span>
`@post.errors.messages[:title]`は配列になっています。

このままだと１個目（`[0]`）しか表示されませんよね？
これは良くないので、以下の様にeach文（CやJavaでのfor文）を使いましょう

```erb
<% if @post.errors.messages[:title].any? %>
  <% @post.errors.messages[:title].each do |message| %>
    <span class="error"><%= message %></span>
  <% end %>
<% end %>
```

2022-02-12 05:54 UTC, gonzaemon111 commented on app/controllers/comments_controller.rb
> +end
ここも`posts_controller`のshowメソッドと同じ内容で、なるべく処理を分割しましょう。

```rb
def destroy
  comment.destroy
  redirect_to post_path(post)
end

private
def post
  @post ||= Post.find(params[:post_id])
end

def comment
  @comment ||= post.comments.find(params[:id])
end
```

2022-02-17 05:04 UTC, nanoGimlet requested changes

2022-02-17 05:04 UTC, nanoGimlet commented on app/models/comment.rb
> +  belongs_to :post, class_name: '::Post'
コメント(comment)は必ず親となる投稿(post)があると思うので、`required: true`を入れましょう。
* [belongs_toにはrequired: trueをつける](https://qiita.com/nikadon/items/41da819f0aa698d74e7d#:~:text=Model-,belongs_to%20%E3%81%AB%E3%81%AF%20required%3A%20true%20%E3%81%BE%E3%81%9F%E3%81%AF%20presence%3A%20true%20%E3%82%92%E3%81%A4%E3%81%91%E3%82%8B,-belongs_to%20%E3%81%A7%E5%BF%85%E3%81%9A)

2022-02-17 07:51 UTC, gonzaemon111 approved these changes

2022-02-17 19:49 UTC, daicha-w commented on app/models/comment.rb
> +  belongs_to :post, class_name: '::Post'
調べてみたところ、Rails5の`belongs_to`ではデフォルトで`required: true`になっているそうなのですが、明示したほうがいいですか？

2022-02-22 00:49 UTC, nanoGimlet commented on app/models/comment.rb
> +  belongs_to :post, class_name: '::Post'
最初なんで意識して欲しいのでつけてみましょう。

2022-02-22 02:19 UTC, daicha-w commented on app/models/comment.rb
> +  belongs_to :post, class_name: '::Post'
了解しました！

2022-02-22 02:24 UTC, nanoGimlet approved these changes

2022-11-09 10:02 UTC, closed without merging